### ISSUE TITLE
Could you provide the relevant files for MGCN?

### ISSUE THREAD

**Issue by chengchenng** [yangxuntu/SGAE#8]
Really appreciate providing the code of such a great work.

 However, when I want to run the code with MGCN modules, the file of 'rela_dict.npy' is lacking.  Could you provide the relevant files?

Thank you very much!!

**Comment by yangxuntu** [comment]
I will check this bug.

**Comment by yangxuntu** [comment]
You can try this code:
python train_mem.py --id id99 --caption_model lstm_mem4 --input_json data/cocobu2.json --input_fc_dir data/cocobu_fc --input_att_dir data/cocobu_att --input_rela_dir data/cocobu_sg_img2 --input_ssg_dir data/coco_spice_sg2 --input_label_h5 data/cocobu2_label.h5 --sg_dict_path data/sg_dict_extend2.npz --batch_size 10 --accumulate_number 10 --learning_rate 5e-4 --learning_rate_decay_start 0 --learning_rate_decay_every 5 --scheduled_sampling_start 0 --checkpoint_path id99 --save_checkpoint_every 5000 --val_images_use 5000 --max_epochs 150 --rnn_size 1000 --input_encoding_size 1000 --att_feat_size 2048 --att_hid_size 512 --self_critical_after 40 --train_split train --memory_size 10000 --memory_index c --step2_train_after 10 --step3_train_after 20 --use_rela 1 --gpu 0 --relu_mod leaky_relu

**Comment by yangxuntu** [comment]
And download the file 'sg_dict_extend2.npz' in the google drive.

**Comment by chengchenng** [comment]
Really thank for your quick help. 

I follow the instructions that you have mentioned. However, the 'rela_dict.npy' is still required.

I suppose when the use_rela is on, line 68 of code in dataloader_extend.py will read the file of rela_dict_dir. This parameter is set in opts which the default setting is 'data/rela_dict.npy'. 

Here is the error(may be helpful): 

tensorboardX is not installed
DataLoader loading json file:  data/cocobu2.json
using new dict
vocab size is  15004
Traceback (most recent call last):
  File "train_mem.py", line 379, in <module>
    train(opt)
  File "train_mem.py", line 36, in train
    loader = DataLoader(opt)
  File "/home/chengc/image-caption/SGAE/dataloader_extend.py", line 68, in __init__
    rela_dict_info = np.load(self.rela_dict_dir,allow_pickle=True)
  File "/home/chengc/anaconda2/envs/SGAE/lib/python2.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
IOError: [Errno 2] No such file or directory: 'data/rela_dict.npy'

**Comment by chengchenng** [comment]
> And download the file 'sg_dict_extend2.npz' in the google drive.

So could you upload the 'rela_dict.npy' in google drive? Thanks!

**Comment by yangxuntu** [comment]
Uploaded.
________________________________
发件人: chengchenng <notifications@github.com>
发送时间: 2019年7月31日 11:32
收件人: yangxuntu/SGAE <SGAE@noreply.github.com>
抄送: #YANG XU# <S170018@e.ntu.edu.sg>; Comment <comment@noreply.github.com>
主题: Re: [yangxuntu/SGAE] Could you provide the relevant files for MGCN? (#8)


And download the file 'sg_dict_extend2.npz' in the google drive.

So could you upload the 'rela_dict.npy' in google drive? Thanks!

―

**Comment by chengchenng** [comment]
> Uploaded.

Thank for your help. Now, the code runs successfully!!

There is one point should be noticed. The --input_rela_dir you mentioned above should be 'data/coco_img_sg' not  'data/cocobu_sg_img2'.  Because the name of the folder after unzip is coco_img_sg. And also the instruction of --input_rela_dir in Readme for training is cocobu_sg_img, I think it should also be coco_img_sg.  Am I right? Or I am using the wrong folder?

Thanks again for your help!

**Comment by yangxuntu** [comment]
I write too many versions before so I am now also a little confusion...
I will check this recently.
________________________________
发件人: chengchenng <notifications@github.com>
发送时间: 2019年7月31日 15:24
收件人: yangxuntu/SGAE <SGAE@noreply.github.com>
抄送: #YANG XU# <S170018@e.ntu.edu.sg>; Comment <comment@noreply.github.com>
主题: Re: [yangxuntu/SGAE] Could you provide the relevant files for MGCN? (#8)


Uploaded.

Thank for your help. Now, the code runs successfully!!

There is one point should be noticed. The --input_rela_dir you mentioned above should be 'data/coco_img_sg' not 'data/cocobu_sg_img2'. Because the name of the folder after unzip is coco_img_sg. And also the instruction of --input_rela_dir in Readme for training is cocobu_sg_img, I think it should also be coco_img_sg. Am I right? Or I am using the wrong folder?

Thanks again for your help!

―
